### ISSUE TITLE
I cant open it 

### ISSUE THREAD

**Issue by TriggerMM** [XternA/income-generator#14] opened 2024-06-07 14:32 UTC
@echo off
setlocal

winget --version >nul 2>&1
if %errorlevel% neq 0 (
    echo No winget found on the system. Please install winget before proceeding.
    exit /b 1
)

wsl --version >nul 2>&1
if %errorlevel% equ 0 (
    wsl [ -d ~/.income-generator ] && wsl "${SHELL##*/}" -ilc "igm" || (
        echo No Income Generator Tool found. Fetching...
        echo:

        wsl git clone --depth=1 https://github.com/XternA/income-generator.git ~/.income-generator
        wsl grep -q "igm='(cd ~/.income-generator; sh start.sh)'" ~/."${SHELL##*/}"rc || (
            wsl echo "alias igm='(cd ~/.income-generator; sh start.sh)'" >> ~/."${SHELL##*/}"rc
            wsl source ~/."${SHELL##*/}"rc
        )

        echo:
        echo Launching...
        timeout /t 2 /nobreak >nul 2>&1
        wsl "${SHELL##*/}" -ilc "igm"
    )
) else (
    echo No Windows Subsystem for Linux found on the system. Ensure WSL is enabled before proceeding.
)

this is what the igm.bat shows when opened with notepad. I have winget installed I have wsl enabled i have docker desktop i have everything enabled i dont understand.

**Comment by TriggerMM** [comment] 2024-06-08 07:50
This shows when I first install the app:  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   939  100   939    0     0   3161      0 --:--:-- --:--:-- --:--:--  3183


and after i type igm it shows this: 

Command 'igm' not found, did you mean:
  command 'ign' from deb ignition-tools (1.4.1+dfsg-2)
  command 'igv' from deb igv (2.12.0+dfsg-1)
  command 'gm' from deb graphicsmagick (1.4+really1.3.38-1ubuntu0.1)
Try: apt install <deb name>
No Income Generator Tool found. Fetching...

fatal: destination path '/root/.income-generator' already exists and is not an empty directory.
The system cannot find the path specified.

Launching...
Command 'igm' not found, did you mean:
  command 'igv' from deb igv (2.12.0+dfsg-1)
  command 'ign' from deb ignition-tools (1.4.1+dfsg-2)
  command 'gm' from deb graphicsmagick (1.4+really1.3.38-1ubuntu0.1)
Try: apt install <deb name>



I tried reinstalling the app and everything needed for it.

NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2.

**Comment by XternA** [comment] 2024-06-10 08:23
Thanks for providing the details. I'll look into it but I think I know what the problem is.

**Comment by TriggerMM** [comment] 2024-06-10 11:20
thank you!

**Comment by XternA** [comment] 2024-06-11 00:15
The issue is fixed now in this PR as reference https://github.com/XternA/income-generator/pull/15.

Please kindly re-run the following command to update the bootstrap script.
```
curl -o %APPDATA%\IGM\igm.bat --create-dirs --ssl-no-revoke -L https://raw.githubusercontent.com/XternA/income-generator/main/start.bat
```

This will replace the current version you have downloaded directly. After that, you can run `igm` again.

Provided as you mentioned you have WSL2 enabled and Ubuntu already installed, this should work now. The problem was with the default `bash` shell not being able to register the tool previously. I use `zsh` so it worked. I think there are some internal changes to the WSL version of Ubuntu and how it loads hence wasn't able to register the alias.

Once the tool loads, kindly update the actual tool just to ensure you're on the latest version since you're starting fresh.
In the tool, `option 9`, `option 5` will update the tool for you if there are any changes.

**Comment by TriggerMM** [comment] 2024-06-11 11:46
everything works now, thank you!

**Comment by XternA** [comment] 2024-06-11 11:53
Perfect, good to know. I will now close this ticket as done.

**Closed** 2024-06-11 11:53 UTC
Labels: bug
